In [1]:
import numpy as np

In [4]:
a = np.random.randint(1, 11, 10)
a

array([2, 2, 8, 1, 9, 9, 8, 6, 9, 3])

In [7]:
n = np.argwhere(a > 3)
print(n)
print(n.flatten())

[[2]
 [4]
 [5]
 [6]
 [7]
 [8]]
[2 4 5 6 7 8]


In [8]:
lst = [1, 2, 3, 4]
lst

[1, 2, 3, 4]

In [9]:
lst = np.delete(lst, [2])
lst

array([1, 2, 4])

In [10]:
lst = np.delete(lst, [])
lst

array([1, 2, 4])

In [12]:
lst = [0]
lst.size

AttributeError: 'list' object has no attribute 'size'